repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/pseewald/fprettify
    rev: v0.3.7
    hooks:
      - id: fprettify
        files: '^src/.*\.(F|f90)$'
